version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openproject-rocketchat
    ports:
      - "8000:8000"  # приложение использует порт 8000
    restart: unless-stopped
